    // Цвета
    export const namedColors = [
        { hex: "#ff0000", name: "Красный",           en: "Red" },
        { hex: "#00ff00", name: "Зелёный",           en: "Green" },
        { hex: "#0000ff", name: "Синий",             en: "Blue" },
        { hex: "#ffff00", name: "Жёлтый",            en: "Yellow" },
        { hex: "#ff00ff", name: "Пурпурный",         en: "Magenta" },
        { hex: "#00ffff", name: "Бирюзовый",         en: "Cyan" },
        { hex: "#800080", name: "Бензиново-синий",   en: "Indigo" },
        { hex: "#ffa500", name: "Оранжевый",         en: "Orange" },
        { hex: "#800000", name: "Марсала",           en: "Maroon" },
        { hex: "#ffc0cb", name: "Розовый",           en: "Pink" },
        { hex: "#ff1493", name: "Глубокий розовый",  en: "Deep Pink" },
        { hex: "#db7093", name: "Бледная фуксия",    en: "Pale Violet Red" },
        { hex: "#fa8072", name: "Лососёвый",         en: "Salmon" },
        { hex: "#e9967a", name: "Тёмный лососевый",  en: "Dark Salmon" },
        { hex: "#ff4500", name: "Огненно-красный",   en: "Orange Red" },
        { hex: "#ff6347", name: "Томатный",          en: "Tomato" },
        { hex: "#cd5c5c", name: "Индийский красный", en: "Indian Red" },
        { hex: "#f08080", name: "Светло-коралловый", en: "Light Coral" },
        { hex: "#ffe4e1", name: "Туманно-розовый",   en: "Misty Rose" },
        { hex: "#fffacd", name: "Лимон-шифон",       en: "Lemon Chiffon" },
        { hex: "#fafad2", name: "Бледно-золотистый", en: "Light Goldenrod Yellow" },
        { hex: "#ffe4b5", name: "Мокасин",           en: "Moccasin" },
        { hex: "#ffdab9", name: "Персиковый",        en: "Peach Puff" },
        { hex: "#ffdead", name: "Навахо-белый",      en: "Navajo White" },
        { hex: "#fff8dc", name: "Кукурузный",        en: "Cornsilk" },
        { hex: "#f5f5dc", name: "Бежевый",           en: "Beige" },
        { hex: "#f0e68c", name: "Хаки",              en: "Khaki" },
        { hex: "#bdb76b", name: "Тёмно-хаки",        en: "Dark Khaki" },
        { hex: "#e6e6fa", name: "Лавандовый",        en: "Lavender" },
        { hex: "#d8bfd8", name: "Черничный",         en: "Thistle" },
        { hex: "#dda0dd", name: "Сливовый",          en: "Plum" },
        { hex: "#da70d6", name: "Орхидея",           en: "Orchid" },
        { hex: "#ee82ee", name: "Фиолетовый",        en: "Violet" },
        { hex: "#ba55d3", name: "Средняя орхидея",   en: "Medium Orchid" },
        { hex: "#9932cc", name: "Тёмная орхидея",    en: "Dark Orchid" },
        { hex: "#8a2be2", name: "Синий-фиолетовый",  en: "Blue Violet" },
        { hex: "#9400d3", name: "Тёмный фиолетовый", en: "Dark Violet" },
        { hex: "#8b008b", name: "Тёмная пурпура",    en: "Dark Magenta" },
        { hex: "#4b0082", name: "Индиго",            en: "Indigo" },
        { hex: "#7b68ee", name: "Средний синий-фиолет", en: "Medium Slate Blue" },
        { hex: "#483d8b", name: "Тёмный сине-фиолетовый", en: "Dark Slate Blue" },
        { hex: "#6a5acd", name: "Синий гранит",          en: "Slate Blue" },
        { hex: "#00ced1", name: "Тёмный бирюзовый",      en: "Dark Turquoise" },
        { hex: "#40e0d0", name: "Бирюзовый",             en: "Turquoise" },
        { hex: "#afeeee", name: "Бледно-бирюзовый",      en: "Pale Turquoise" },
        { hex: "#20b2aa", name: "Светло-морская волна",  en: "Light Sea Green" },
        { hex: "#2e8b57", name: "Тёмно-морской зелёный", en: "Sea Green" },
        { hex: "#3cb371", name: "Средне-морской зелёный", en: "Medium Sea Green" },
        { hex: "#2f4f4f", name: "Тёмно-серый",           en: "Dark Slate Gray" },
        { hex: "#556b2f", name: "Тёмно-оливковый",       en: "Dark Olive Green" },
        { hex: "#6b8e23", name: "Оливковый",             en: "Olive Drab" },
        { hex: "#808000", name: "Оливковый жёлтый",      en: "Olive" },
        { hex: "#9acd32", name: "Жёлто-зелёный",         en: "Yellow Green" },
        { hex: "#7fff00", name: "Ярко-зелёный",          en: "Chartreuse" },
        { hex: "#00ff7f", name: "Мятно-зелёный",         en: "Spring Green" },
        { hex: "#228b22", name: "Лесной зелёный",        en: "Forest Green" },
        { hex: "#006400", name: "Тёмно-зелёный",         en: "Dark Green" },
        { hex: "#008080", name: "Бирюзово-зелёный",      en: "Teal" },
        { hex: "#008b8b", name: "Тёмный циан",           en: "Dark Cyan" },
        { hex: "#000080", name: "Тёмно-синий",           en: "Navy" },
        { hex: "#00008b", name: "Тёмно-синий",           en: "Dark Blue" },
        { hex: "#4169e1", name: "Насыщенный синий",      en: "Royal Blue" },
        { hex: "#1e90ff", name: "Додж-синий",           en: "Dodger Blue" },
        { hex: "#87ceeb", name: "Небесно-голубой",       en: "Sky Blue" },
        { hex: "#6495ed", name: "Кобальтовый",          en: "Cornflower Blue" },
        { hex: "#00bfff", name: "Средний небесный синий", en: "Deep Sky Blue" },
        { hex: "#4682b4", name: "Стальной синий",        en: "Steel Blue" },
        { hex: "#5f9ea0", name: "Кадетский синий",       en: "Cadet Blue" },
        { hex: "#b0c4de", name: "Светло-стальной синий",  en: "Light Steel Blue" }
      ];
      
  //градиенты
  export const predefinedGradients = [
    { colors: ["#ff9a9e", "#fad0c4"], name: "Розово-персиковый",      en: "Pink-Peach" },
    { colors: ["#a18cd1", "#fbc2eb"], name: "Лавандовый",             en: "Lavender" },
    { colors: ["#84fab0", "#8fd3f4"], name: "Морской бриз",           en: "Sea Breeze" },
    { colors: ["#ff9a9e", "#ffc3a0"], name: "Розово-абрикосовый",      en: "Pink-Apricot" },
    { colors: ["#ffecd2", "#fcb69f"], name: "Персиковый закат",       en: "Peach Sunset" },
    { colors: ["#e0c3fc", "#8ec5fc"], name: "Фиолетово-голубой",      en: "Purple-Blue" },
    { colors: ["#f6d365", "#fda085"], name: "Солнечный закат",        en: "Sunset Glow" },
    { colors: ["#ff9a9e", "#fecfef"], name: "Нежный розовый",         en: "Soft Pink" },
    { colors: ["#a1c4fd", "#c2e9fb"], name: "Небесный градиент",      en: "Sky Gradient" },
    { colors: ["#667eea", "#764ba2"], name: "Синий фиолетовый",       en: "Blue Violet" },
    { colors: ["#89f7fe", "#66a6ff"], name: "Ледяной синий",          en: "Ice Blue" },
    { colors: ["#f7797d", "#FBD786"], name: "Кораллово-жёлтый",       en: "Coral Yellow" },
    { colors: ["#43cea2", "#185a9d"], name: "Морской синий",          en: "Sea Blue" },
    { colors: ["#30cfd0", "#330867"], name: "Бирюзово-тёмный",        en: "Turquoise Dark" },
    { colors: ["#f093fb", "#f5576c"], name: "Розово-лавандовый",      en: "Pink Lavender" },
    { colors: ["#5ee7df", "#b490ca"], name: "Туманная сирень",         en: "Misty Lilac" },
    { colors: ["#c471f5", "#fa71cd"], name: "Сиренево-розовый",      en: "Lilac Pink" },
    { colors: ["#fa709a", "#fee140"], name: "Розово-жёлтый",          en: "Pink Yellow" },
    { colors: ["#43e97b", "#38f9d7"], name: "Зелёно-бирюзовый",       en: "Green Turquoise" },
    { colors: ["#fa8bff", "#2bd2ff"], name: "Розово-голубой",         en: "Pink Cyan" },
    { colors: ["#f5af19", "#f12711"], name: "Золотой градиент",       en: "Golden Gradient" },
    { colors: ["#30cfd0", "#330867"], name: "Бирюзово-фиолетовый",    en: "Turquoise Purple" },
    { colors: ["#ff9a9e", "#fecfef"], name: "Пастельно-розовый",      en: "Pastel Pink" },
    { colors: ["#a18cd1", "#fbc2eb"], name: "Лилово-розовый",         en: "Lilac Pink" },
    { colors: ["#667eea", "#764ba2"], name: "Королевский фиолет",     en: "Royal Purple" },
    { colors: ["#fddb92", "#d1fdff"], name: "Жёлто-голубой",          en: "Yellow Blue" },
    { colors: ["#e2b0ff", "#9f44d3"], name: "Пурпурный градиент",     en: "Purple Gradient" },
    { colors: ["#c21500", "#ffc500"], name: "Горячий градиент",       en: "Hot Gradient" },
    { colors: ["#667eea", "#764ba2"], name: "Сиреневый синий",        en: "Lavender Blue" },
    { colors: ["#ffecd2", "#fcb69f"], name: "Пастельно-персиковый",   en: "Pastel Peach" },
    { colors: ["#89f7fe", "#66a6ff"], name: "Голубой лёд",            en: "Blue Ice" },
    { colors: ["#f093fb", "#f5576c"], name: "Виноградный",            en: "Grape" },
    { colors: ["#30cfd0", "#330867"], name: "Пурпурный бирюзовый",    en: "Purple Turquoise" },
    { colors: ["#feada6", "#f5efef"], name: "Кремово-розовый",        en: "Creamy Pink" },
    { colors: ["#a1c4fd", "#c2e9fb"], name: "Голубое утро",           en: "Blue Morning" },
    { colors: ["#ff9a9e", "#fecfef"], name: "Розовый коктейль",       en: "Pink Cocktail" },
    { colors: ["#cfd9df", "#e2ebf0"], name: "Пепельно-голубой",       en: "Ash Blue" },
    { colors: ["#ffecd2", "#fcb69f"], name: "Кремовый персик",        en: "Cream Peach" },
    { colors: ["#89f7fe", "#66a6ff"], name: "Весенний день",          en: "Spring Day" },
    { colors: ["#f093fb", "#f5576c"], name: "Розовое облако",         en: "Pink Cloud" },
    { colors: ["#30cfd0", "#330867"], name: "Морской закат",          en: "Sea Sunset" },
    { colors: ["#e0c3fc", "#8ec5fc"], name: "Лавандово-голубой",      en: "Lavender Blue" },
    { colors: ["#ff9a9e", "#fecfef"], name: "Нежный закат",           en: "Soft Sunset" },
    { colors: ["#a18cd1", "#fbc2eb"], name: "Пыльная сирень",         en: "Dusty Lilac" },
    { colors: ["#84fab0", "#8fd3f4"], name: "Океанический",           en: "Oceanic" },
    { colors: ["#f6d365", "#fda085"], name: "Мягкий закат",           en: "Soft Sunset" },
    { colors: ["#ff9a9e", "#fecfef"], name: "Песочно-розовый",        en: "Sand Pink" },
    { colors: ["#89f7fe", "#66a6ff"], name: "Ледяной градиент",       en: "Ice Gradient" },
    { colors: ["#cfd9df", "#e2ebf0"], name: "Туманное утро",          en: "Foggy Morning" },
    { colors: ["#ffecd2", "#fcb69f"], name: "Закатный свет",          en: "Sunset Light" },
    { colors: ["#e2b0ff", "#9f44d3"], name: "Фиолетово-лиловый",      en: "Violet Lilac" },
    { colors: ["#30cfd0", "#330867"], name: "Глубокий океан",         en: "Deep Ocean" },
    { colors: ["#89f7fe", "#66a6ff"], name: "Яркий лёд",              en: "Bright Ice" },
    { colors: ["#ff9a9e", "#fad0c4"], name: "Коралл и нектарин",      en: "Coral & Nectarine" },
    { colors: ["#fbd3e9", "#bb377d"], name: "Ягодный щербет",         en: "Berry Sorbet" },
    { colors: ["#74ebd5", "#acb6e5"], name: "Морская пена", en: "Sea Foam" },
    { colors: ["#ff6a00", "#ee0979"], name: "Пылающий закат", en: "Blazing Sunset" },
    { colors: ["#12c2e9", "#c471ed"], name: "Арктический фиолет", en: "Arctic Purple" },
    { colors: ["#0fd850", "#f9f047"], name: "Лайм и лимон", en: "Lime Lemon" },
    { colors: ["#fc6076", "#ff9a44"], name: "Коралловый свет", en: "Coral Light" },
    { colors: ["#00f2fe", "#4facfe"], name: "Голубая лагуна", en: "Blue Lagoon" },
    { colors: ["#7f00ff", "#e100ff"], name: "Фиолетовый взрыв", en: "Purple Burst" },
    { colors: ["#f7971e", "#ffd200"], name: "Апельсиновый день", en: "Orange Day" },
    { colors: ["#4ca1af", "#c4e0e5"], name: "Северный лёд", en: "Northern Ice" },
    { colors: ["#ff5f6d", "#ffc371"], name: "Розовый закат", en: "Pink Sunset" },
    { colors: ["#00c6ff", "#0072ff"], name: "Глубокое море", en: "Deep Sea" },
    { colors: ["#2193b0", "#6dd5ed"], name: "Летний бриз", en: "Summer Breeze" },
    { colors: ["#e65c00", "#f9d423"], name: "Огненный песок", en: "Fiery Sand" },
    { colors: ["#ec008c", "#fc6767"], name: "Малиновый шторм", en: "Raspberry Storm" },
    { colors: ["#3a1c71", "#d76d77", "#ffaf7b"], name: "Закатный градиент", en: "Sunset Gradient" },
    { colors: ["#bdc3c7", "#2c3e50"], name: "Графитовый серый", en: "Graphite Gray" },
    { colors: ["#de6161", "#2657eb"], name: "Грозовой горизонт", en: "Storm Horizon" },
    { colors: ["#ff4e50", "#f9d423"], name: "Тропический микс", en: "Tropical Mix" },
    { colors: ["#1d4350", "#a43931"], name: "Осенняя бронза", en: "Autumn Bronze" },
    { colors: ["#4b6cb7", "#182848"], name: "Полуночный лёд", en: "Midnight Ice" },
    { colors: ["#bc4e9c", "#f80759"], name: "Фуксия и малина", en: "Fuchsia Raspberry" },
    { colors: ["#355c7d", "#6c5b7b", "#c06c84"], name: "Сумерки", en: "Twilight" },
    { colors: ["#2980b9", "#6dd5fa", "#ffffff"], name: "Лёгкое небо", en: "Light Sky" },
    { colors: ["#00c3ff", "#ffff1c"], name: "Электро радуга", en: "Electro Rainbow" },
    { colors: ["#ed4264", "#ffedbc"], name: "Клубничный пломбир", en: "Strawberry Ice Cream" },
    { colors: ["#c6ffdd", "#fbd786", "#f7797d"], name: "Летний рассвет", en: "Summer Dawn" },
    { colors: ["#1a2a6c", "#b21f1f", "#fdbb2d"], name: "Горизонт", en: "Horizon" },
    { colors: ["#833ab4", "#fd1d1d", "#fcb045"], name: "Инстаграм", en: "Instagram" },
    { colors: ["#ff9a8b", "#ff6a88", "#ff99ac"], name: "Сахарная вата", en: "Cotton Candy" },
    { colors: ["#cc2b5e", "#753a88"], name: "Имперская слива", en: "Imperial Plum" },
    { colors: ["#ee9ca7", "#ffdde1"], name: "Молочный розовый", en: "Milky Pink" },
    { colors: ["#d9a7c7", "#fffcdc"], name: "Шелковый рассвет", en: "Silky Dawn" },
    { colors: ["#ff6e7f", "#bfe9ff"], name: "Зефир", en: "Marshmallow" },
    { colors: ["#4b79a1", "#283e51"], name: "Холодная ночь", en: "Cold Night" },
    { colors: ["#2b5876", "#4e4376"], name: "Мистический синий", en: "Mystic Blue" },
    { colors: ["#43c6ac", "#191654"], name: "Изумрудная ночь", en: "Emerald Night" },
    { colors: ["#ffecd2", "#fcb69f"], name: "Лёгкий персик", en: "Light Peach" },
    { colors: ["#b92b27", "#1565c0"], name: "Огненно-синий", en: "Fire Blue" },
    { colors: ["#2196f3", "#f44336"], name: "Контраст", en: "Contrast" },
    { colors: ["#e96443", "#904e95"], name: "Медный вечер", en: "Copper Evening" },
    { colors: ["#0b486b", "#f56217"], name: "Пылающее море", en: "Burning Sea" },
    { colors: ["#8e2de2", "#4a00e0"], name: "Сияющая орхидея", en: "Radiant Orchid" },
    { colors: ["#56ab2f", "#a8e063"], name: "Весенняя зелень", en: "Spring Green" },
    { colors: ["#614385", "#516395"], name: "Индиго пыль", en: "Indigo Dust" },
    { colors: ["#f00000", "#dc281e"], name: "Пылающий красный", en: "Burning Red" },
    { colors: ["#00c9ff", "#92fe9d"], name: "Голубой луг", en: "Blue Meadow" },
    { colors: ["#f2709c", "#ff9472"], name: "Теплый коралл", en: "Warm Coral" }
  ];